spring.application.name=BankManage
spring.datasource.url=jdbc:mysql://localhost:3306/BankDB
spring.datasource.username=root
spring.datasource.password=Zlatan@19951108
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
